application:
  name: customer

server:
  port: 8081

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    driverClassName: org.postgresql.Driver
    username: postgres
    password: