application:
  name: customer

server:
  port: 8081


spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    queue:
      name: firstqueue
    exchange:
      name: firstexchange
    routing:
      key: firstkey

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234